### ISSUE TITLE
Add example to README

### ISSUE THREAD

**Issue by stuaxo** [begnac/gasyncio#1]
Hi,
  Any chance you could add a more full example to the README ?

Cheers
S

**Comment by begnac** [comment]
Of course.  Done.

Le dimanche 21 mars 2021 à 07:40 -0700, Stuart Axon a écrit :

**Comment by begnac** [comment]
For a more complete example, check out [this](https://github.com/begnac/ampd/blob/main/examples/ampc-gtk) toy app.  Of course course the [ampd](https://github.com/begnac/ampd) package was meant for doing more than this, I might upload the real app soon :)

**Comment by stuaxo** [comment]
Interesting.
I guess the callbacks happen out of band, from asyncio so can't be async methods ?

**Comment by begnac** [comment]
Callbacks are (usually) actual functions, but of course they may schedule a new async task.
