### ISSUE TITLE
comparison with asyncio-glib

### ISSUE THREAD

**Issue by nlgranger** [begnac/gasyncio#2]
How does this projection compare to https://github.com/jhenstridge/asyncio-glib ?

**Comment by begnac** [comment]
In gasyncio, the main loop is the GLib one, and the asyncio is stepped inside it when necessary.  If I understand correctly the README, asyncio-glib goes the other way around.
But really, the main feature of gasyncio is that it covers my use case.  I haven't had any reports, but if you find something that's missing I'd be happy to add it (if that makes sense).

**Comment by nlgranger** [comment]
All right, thank you.
