### ISSUE TITLE
Compatibility with windows

### ISSUE THREAD

**Issue by martinKupec** [begnac/gasyncio#3]
The current code doesn't work on windows.

Problem is with "GLib.IOChannel.unix_new(key.fd)". This is supposed to work on windows, but at least for me it does not.

Here is a simple fix to make it work in basic scenarios.
The problem is, that it will not work when "register" is called with file descriptor instead of socket descriptor.
First call of "register" is internal and is with socket descriptor.

```
diff --git a/gasyncio/gevents.py b/gasyncio/gevents.py
index 309c0e7..63806eb 100644
--- a/gasyncio/gevents.py
+++ b/gasyncio/gevents.py
@@ -31,6 +31,7 @@ class GAsyncIOSelector(selectors._BaseSelectorImpl):
         super().__init__()
         self._sources = {}
         self._ready = []
+        self.is_win32 = sys.platform == 'win32'
 
     @staticmethod
     def _events_to_io_condition(events):
@@ -44,7 +45,10 @@ class GAsyncIOSelector(selectors._BaseSelectorImpl):
 
     def register(self, fileobj, events, data):
         key = super().register(fileobj, events, data)
-        io_channel = GLib.IOChannel.unix_new(key.fd)
+        if self.is_win32:
+            io_channel = GLib.IOChannel.win32_new_socket(key.fd)
+        else:
+            io_channel = GLib.IOChannel.unix_new(key.fd)
         io_channel.set_encoding(None)
         io_channel.set_buffered(False)
         source = GLib.io_add_watch(io_channel, GLib.PRIORITY_DEFAULT, self._events_to_io_condition(events), self._channel_watch_cb, key)
```

**Comment by begnac** [comment]
Hello, yes, I am purely a linux user.
I added your suggested change, with the test for win32 somewhat moved, can you check this works for you ?
Cheers,
I.

**Comment by martinKupec** [comment]
Hi it work great, at least for me.

But I have found another issue occuring at least on windows, but this time the fix will also alter behavior on linux

```
diff --git a/gasyncio/gevents.py b/gasyncio/gevents.py
index 8d253a4..c0d3147 100644
--- a/gasyncio/gevents.py
+++ b/gasyncio/gevents.py
@@ -154,7 +154,13 @@ class GAsyncIOEventLoop(asyncio.selector_events.BaseSelectorEventLoop):
         timer = asyncio.events.TimerHandle(when, callback, args, self, context)
         if timer._source_traceback:
             del timer._source_traceback[-1]
-        timer._scheduled = GLib.timeout_add((when - self.time()) * 1000, self._timeout_cb, timer)
+        timeout = timer.when() - self.time()
+        if timeout < 0:
+            # Pick some arbitrary small number, zero is usually too small
+            timeout = 1
+        else:
+            timeout = int(timeout * 1000)
+        timer._scheduled = GLib.timeout_add(timeout, self._timeout_cb, timer)
         return timer
 
     def _timer_handle_cancelled(self, timer):
```

For some reason it may happen, that "when" is older than now and timeout_add don't like negative values. Adding zero may be a solution, but adding something slightly higher lowers the priority of the call.

**Comment by begnac** [comment]
Are you sure about zero giving higher priority?  Docs say it's  G_PRIORITY_DEFAULT regardless, no ?
But you are entirely right about not sending negative delay.

**Comment by begnac** [comment]
Just pushed, please check.  And thanks !

**Comment by martinKupec** [comment]
There is no "priority" involved. Just non-zero number is "later" than "zero".
The problem here is, that when call_later "delay" is close to zero it will translate to negative or really small "timeout" in my patch.
I do set timeout to "1" instead of "0" as "0" means "now" and when you keep scheduling "near zero" events it floods the loop and GUI starts to be unusable.

I have tested your patches, first one (#48e39c95) was a bit wrong (still corner-case with possible negative delay), but the second one (#a222f3348) seems to work just fine.

**Comment by begnac** [comment]
Yeah, I realised what the problem was just after posting it.  OK, if this works then I am closing the issue.  Thanks !
